### ISSUE TITLE
[Question] [Support needed] Is this project dead or alive? 

### ISSUE THREAD

**Issue by hellboy81** [jeffreyabecker/FluentMigrator.NHibernate#3]
Is this project production ready?

Why should I **not**  use  [alternative](https://github.com/fluentmigrator/fluentmigrator) ?

**Comment by jeffreyabecker** [comment]
I wouldn't use it for a production project. Im personally sick of fluent
migrator & working on a different solution. Fork it if you want.

**Comment by jeffreyabecker** [comment]
Just To be clear: If you want migrations, use Fluent Migrator. If you want something to help you make fluent migrator migrations from NHibernate, Fork this and have fun. I'm not working on it any more.
