### ISSUE TITLE
Replace OnTable to FromTable

### ISSUE THREAD

**Issue by megafetis** [jeffreyabecker/FluentMigrator.NHibernate#4]
Need to replace OnTable to FromTable method in migration generation

**Comment by megafetis** [comment]
@jeffreyabecker please correct methods: from "OnTable()" to "FromTable()" and finish dotnet-nh tool. Thank you

**Comment by jeffreyabecker** [comment]
Per previous comments I have abandoned work on this project. If you want it fixed please fork and submit a pull request.
